FROM node:8
RUN useradd --uid 1100 nodeusr
ADD yarn.lock /yarn.lock
ADD package.json /package.json
ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn
USER 1100
WORKDIR /app
ADD . /app
EXPOSE 3000
ENTRYPOINT ["/bin/bash", "/app/run.sh"]
CMD ["start"]